repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.2'
    hooks:
      - id: poetry-lock
        args: [ "--no-update" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8_deps
          - flake8-bandit==4.1.1
          - flake8-broken-line==0.6.0
          - flake8-comprehensions==3.10.1
          - flake8-class-attributes-order==0.1.3
          - flake8-eradicate==1.4.0
          - pep8-naming==0.13.3
          - flake8-functions==0.0.7
          - flake8-annotations==3.0.0
          - flake8-fixme==1.1.1
          - flake8-tidy-imports==4.8.0
          - flake8-simplify==0.19.3
          - flake8-bugbear==23.1.20
          - flake8-type-checking==2.3.0
          - flake8-rst-docstrings==0.3.0
          - darglint==1.8.1
          - flake8-docstrings==1.6.0

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
      - id: python-check-blanket-type-ignore

  - repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [ "--in-place", "--wrap-summaries", "100" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: *flake8_deps
